name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Actualizando Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Instalando dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Corriendo pytest
        run: |
          pytest tests/test_belly.py --maxfail=1 --disable-warnings -q

      - name: Corriendo behave spanish
        run: |
          python3 -m behave --tags=@spanish
          
      - name: Corriendo behave english
        run: |
          python3 -m behave --tags=@english

