name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Actualizando Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Instalando dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Corriendo pytest
        run: |
          pytest tests/test_belly.py --maxfail=1 --disable-warnings -q

      - name: Corriendo behave spanish
        run: |
          python3 -m behave --tags=@spanish || exit 1
          
      - name: Corriendo behave english
        run: |
          python3 -m behave --tags=@english || exit 1
          
      - name: Prueba 1000 pepinos
        run: |
          echo "Iniciando prueba"
          start=$(date +%s)
          behave -n "Comer 1000 pepinos y esperar 10 horas"
          end=$(date +%s)
          duracion=$((end - start))
          echo "Prueba completada"
          if ["$duracion" -gt 10]; then
            echo "Cuidado, la prueba tardo mucho: ${duracion} s"
            exit 1
          fi

